---
apiVersion: kubeflow.org/v1alpha1
kind: TFJob
metadata:
  name: dist-unet
  namespace: kubecon
spec:
  replicaSpecs:
  - replicas: 3
    template:
      spec:
        containers:
        - args:
          - --epochs
          - "10"
          image: docker.io/raddaoui/tfjob_unet_distributed:2.0
          name: tensorflow
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: gcs-creds
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: gcs-creds
                key: AWS_SECRET_ACCESS_KEY
          - name: AWS_REGION
            value: "us-west-1"
          - name: S3_REGION
            value: "us-west-1"
          - name: S3_USE_HTTPS
            value: "true"
          - name: S3_VERIFY_SSL
            value: "true"
          - name: S3_ENDPOINT
            value: "storage.googleapis.com"
          - name: OUTPUT_PATH
            value: "s3://alakubecon/distunet"
          volumeMounts:
          - name: dataset-storage
            mountPath: /tmp/data
        restartPolicy: OnFailure
        volumes:
        - name: dataset-storage
          persistentVolumeClaim:
           claimName: unet-dataset
           readOnly: true
    tfReplicaType: WORKER
  - replicas: 1
    template:
      spec:
        containers:
        - args:
          - --epochs
          - "10"
          image: docker.io/raddaoui/tfjob_unet_distributed:2.0
          name: tensorflow
        restartPolicy: OnFailure
    tfReplicaType: PS
  terminationPolicy:
    chief:
      replicaIndex: 0
      replicaName: WORKER
