apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
  creationTimestamp: 2018-04-25T07:14:04Z
  labels:
    failure-domain.beta.kubernetes.io/region: us-west1
    failure-domain.beta.kubernetes.io/zone: us-west1-a
  name: pvc-3a40b2d1-4858-11e8-947f-42010a8a0151
  resourceVersion: "48495"
  selfLink: /api/v1/persistentvolumes/pvc-3a40b2d1-4858-11e8-947f-42010a8a0151
  uid: 3caa770d-4858-11e8-947f-42010a8a0151
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 19Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: unet-dataset
    namespace: kubeflow
    resourceVersion: "48487"
    uid: 3a40b2d1-4858-11e8-947f-42010a8a0151
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-ala-kubecon-a0d369-pvc-3a40b2d1-4858-11e8-947f-42010a8a0151
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
status:
  phase: Bound
